print ('Simon')
# echo simon
print ('Ivo')
print ('Chidi')
print ('Grace')
print ('Glory')
print ('LSS')
print ('DevOps')
print ('car services automated')
print ('hello $user your car need servcing')
print ('bugs locate in applcation')
print ('bugs removed from application')
